basarat/typescript-book

code/es6/classes/class.js, code/es6/classes/class.ts, docs/classes.md
Hey - there was a little typo in the ts which filtered down to the generated js as well.
=> Fix minor typos in classes section.

docs/classes.md
fixing typos in Access Modifiers - sample
=> syntax typos

docs/const.md
=> Fixed mutated sub properties sentence.

docs/getting-started.md
=> Fixed DefinitelyTyped reference. Added link.

docs/types/freshness.md
I think this is in the latest 1.7 release IIRC.  Thanks for the book!
=> Remove note about requiring nightly for freshness

docs/types/type-assertion.md
=> cleanup grammar

docs/spread-operator.md
Hi, this got my attention while reading through your book.
=> Minor typo fix

docs/template-strings.md
Remove word from example of template-strings using expressions.
=> Remove ekstra console.log word in template-strings

docs/staging/iterators.md
Iterators draft mentioned in #81. I hope that it is helpful. Probably needs a link to some JS documentation describing symbols. Say to the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
=> Add Iterators draft

SUMMARY.md, code/es6/iterators.js, code/es6/iterators.ts, code/tips/tsconfig.json, docs/iterators.md
- add a note about using Iterators with ES5 target
=> Add Iterators section after for..of

docs/destructuring.md
Added an example on how to assign a new variable name to an extracted variable..
=> Object Destructuring assign new variable name

docs/tips/typeInstantiation.md
The behavior is "not" the same after a change, not "now" the same
=> typos in typeInstantiation

docs/types/readonly.md
Reverts basarat/typescript-book#109
=> Revert "Added TypeScript version warning for readonly feature"

docs/quick/nodejs.md
Fix to account for changes to typings API
=> Update command to install node typings

docs/javascript/recap.md
the good new ~> the good news.
the book is awesome! thanks
=> fixed small typo

docs/generators.md
=> Update generators.md to correct typo

docs/javascript/recap.md
"then" should be "than" in this instance :)
=> Fixing small typo

docs/tips/singleton.md
Since TypeScript 2.0, constructor can be private. 
https://www.typescriptlang.org/docs/release-notes/typescript-2.0.html
=> Use private constructor for Singleton pattern

docs/javascript/recap.md
=> "bug" -> "bugs" in recap.md

docs/promise.md
* Parameter for `loadItem` was not typed correctly
* fixed function name typo
=> Fix chaining example

.gitignore, docs/classes-emit.md
**Added typo fixes for classes-emit.md**
Also:
- added .DS_Store to .gitignore
=> Typo fixes for classes-emit.md

docs/arrow-functions.md, docs/classes-emit.md, docs/let.md
**This pull request updates text in let.md, classes-emit.md and 	code examples in arrow-functions.md**
=> Updated text in let.md, classes-emit.md and 	code examples in arrow-functions.md

docs/arrow-functions.md, docs/const.md, docs/let.md
**This pull request fixes punctuation and several typos**
Details:
- fixed several typos in _arrow-functions.md_
- fixed punctuation in _let.md_
- fixed typo in _const.md_
=> Fixed punctuation and several typos

docs/destructuring.md, docs/for...of.md
**This pull request updates text in fixed some typos**
=> Updated text in fixed some typos

docs/types/lib.d.ts.md
=> fix some typos

docs/promise.md, docs/spread-operator.md
**This pull request adds text fixes for _spread-operator.md_ and _promise.md_**
=> Fixes for spread-operator.md and promise.md

docs/async-await.md, docs/promise.md
**This pull request adds more fixes to _promise.md_ and _async-await.md_**
=> More fixes to promise.md and async-await.md

docs/generators.md, docs/project/declarationspaces.md, docs/project/external-modules.md, docs/project/files.md, docs/project/tsconfig.md
Details:
- added fixes for _generators.md_
- added fixes for _external-modules.md_
- added fixes for _declarationspaces.md_
- added fixes for _files.md_
- added fixes for _tsconfig.md_
=> Added more text fixes

docs/project/namespaces.md, docs/types/type-system.md
Details:
- added fixes for _namespaces.md_
- added fixes for _type-system.md_
=> Added text fixes for namespaces.md and type-system.md

docs/types/@types.md, docs/types/ambient/intro.md, docs/types/migrating.md
Details:
- added fixes for _migrating.md_
- added fixes for _@types.md_
- added fixes for _intro.md_
=> Added fixes to migrating.md, @types.md, intro.md

docs/types/ambient/d.ts.md, docs/types/ambient/variables.md
Details:
- added fixes for _d.ts.md_
- added fixes for _variables.md_
=> Added fixes for d.ts.md, variables.md

docs/types/ambient/variables.md, docs/types/interfaces.md
Details:
- reverted semicolons after interfaces in _variables.md_
- added fixes for _interfaces.md_
=> Added more text fixes for variables.md, interfaces.md

docs/types/ambient/variables.md
Looks like it's been moved within in the repo, corrected link.
=> Update node.d.ts link

docs/enums.md, docs/project/globals.md
**This pull request adds fixes to _globals.md_ and _enums.md_**
=> Added fixes to globals.md and enums.md

docs/promise.md
I fixed some minor whitespace issues I found in the promise chapter code examples.
=> Fix whitespace in promise chapter

docs/async-await.md
The thought experiment *is actually real* and is the `async`/`await` implementation in TypeScript / JavaScript.
The thought experiment *is actually real* and **so** is the `async`/`await` implementation in TypeScript / JavaScript.
=> doc: update async-await.md

docs/enums.md, docs/types/lib.d.ts.md
**This pull request adds fixes to _enums.md_ and _lib.d.ts.md_**
=> Added fixes to enums.md and lib.d.ts.md

docs/types/functions.md, docs/types/type-assertion.md
**This pull request adds fixes for functions.md and type-assertion.md**
=> Added fixes for functions.md and type-assertion.md

docs/types/freshness.md, docs/types/functions.md, docs/types/type-assertion.md, docs/types/typeGuard.md
**This pull request adds fixes for functions.md, type-assertion.md, freshness.md, typeGuard.md**
=> Added fixes for functions.md, type-assertion.md, freshness.md, typeGuard.md

docs/promise.md
See: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
=> Correct terminology

docs/promise.md, docs/types/generics.md, docs/types/literal-types.md, docs/types/readonly.md
**This pull request adds fixes for promise.md, literal-types.md, readonly.md, generics.md**
=> Added fixes for promise.md, literal-types.md, readonly.md, generics.md

docs/project/namespaces.md
Otherwise you'll get a [reference error].(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_assignment_left-hand_side)
=> Wrap something default assignment in parentheses 

docs/compiler/binder-symboltable.md
I noticed a small spelling error while reading.  Thanks for such a great resource!  This book is really invaluable.
=> Fix spelling typo

docs/project/tsconfig.md
Created with typescript --init (new in TypeScript 2.3)
=> All options in TypeScript 2.3 tsconfig.json

docs/destructuring.md
Will error without outer parentheses  http://stackoverflow.com/a/34836155/502851
=> Object destructuring to existing variables

docs/types/generics.md
Nothing crazy, just a bit of typo fixes here. Will try to keep the amount of commits of this type down in the future (more fixes per commit).
=> Typo fixes in generics.md

docs/types/readonly.md
the property can modified because of aliasing => the property can be modified because of aliasing.
=> Small typo fix to readonly.md

docs/quick/browser.md
https://github.com/webpack/webpack/issues/4549
=> Browser QuickStart: webpack config example fix

docs/quick/nodejs.md
Added some box-drawing for the project layout in `/docs/quick/nodejs.md`
https://en.wikipedia.org/wiki/Box-drawing_character
Thanks
=> Use box-drawing

docs/compiler/ast-trivia.md
This sentence is the exact wording of the two points listed above
=> Removed duplicated ownership information

docs/compiler/program.md
=> Apostrophe type removed

docs/quick/nodejs.md
This adds the actual tsconfig.json configuration option for including TypeScript source files from the "src" directory for compiling.
=> Add actual tsconfig.json configuration option.

code/types/freshness/index-signatures.ts, docs/styleguide/styleguide.md, docs/types/discriminated-unions.md, docs/types/index-signatures.md
=> Update typos and grammar

docs/spread-operator.md
=> Fix typo in Spread Operator chapter

docs/quick/nodejs.md
In tsconfig.json file, the `include` section bug fixed and the quotation position changed.
=> tsconfig.json include section bug fixed

docs/options/strictNullChecks.md
I took some liberties here. But I think it is a little clearer with my changes 🌤
=> Improve wording of strictNullChecks section

docs/javascript/number.md
Number.MIN_VALUE is the smallest representable positive value.
=> Fix number.md to correctly explain Number.MIN_VALUE and Number.MAX_VALUE

book.json, docs/async-await.md, docs/getting-started.md, docs/javascript/recap.md, docs/project/dynamic-import-expressions.md, docs/promise.md, docs/tips/outFile.md, docs/types/freshness.md, header.html
=> Fixes EPUB Validation Issues, allows for uploading to Google Play Books

docs/getting-started.md
=> fixed alm link

docs/testing/intro.md
=> Removed extraneous 'k'

README.md
Included the link under the "translations" part for the Filipino translations
=> Added Filipino translation

README.md
Hi, im' currently translating this in italian in my fork.
Like the Filipino translation, i would just want to add the link and keep translating in my fork, let me know if this is ok
=> Italian Translation

docs/classes-emit.md
because information sounds weird here
=> information -> fact

docs/tools/husky.md
=> fixed typo

docs/types/index-signatures.md
=> Update index-signatures.md (typo fixed)

docs/promise.md
One quick typo fix: preceeding -> preceding
Great resource here, thanks!
=> Update promise.md - typo fix

docs/template-strings.md
Should this PR also update the code in code/es6/template-strings.ts?
=> Add types to tagged template example

docs/quick/nodejs.md
The problem is that using --include with recent versions of `tsc` throws the following error:
`error TS5023: Unknown compiler option '--include'.`
=> Fixes initialization of tsconfig.json

README.md
Hi,
I'm working on russian translation you are amazing book, i hope you add link on my work.
=> Add link on russian translate

docs/project/external-modules.md
=> Fix a typo

README.md
Hi,
Thank you for writing this amazing book.
I'm working on Japanese translation and I hope you add link on my work.
=> Adding japanese translation

docs/javascript/null-undefined.md
Understanding how null/undefined work with JSON encoding and remote databases is something I'd wish I known about when I first read through this and opted to go exclusively with undefined.
=> Add a JSON section to discussion of null vs undefined

README.md
Regarding https://github.com/basarat/typescript-book/issues/487, I'd like to do this on my own fork. I'm adding the link to it for the README on this PR. Hope it's ok!
=> link to spanish version

README.md
hi korean link add. korean is in translation
=> Korean translation link add

docs/javascript/recap.md
Thanks for this project!
Fixes some correctness, spelling and grammar errors from 0dd1e6bace619de125a37a0664380c1ea2adc75f.
Ref: #358
=> Fix correctness and grammar

docs/errors/interpreting-errors.md
I think it's just misspelled.
**Thank you so much for making the amazing repo!**
=> fix s/succint/succinct/

docs/testing/jest.md
Based on the `'../'`, I assumed that the test files are all in the `src/__test__` directory.
=> Fix import error

docs/javascript/recap.md
The sentence was not able to be read clearly
=> fix typo: change comma to and

README.md
Hi, many thanks for your great job with this book.
I've started to translate the french version, can you add my link please ?
=> Add link french translation

docs/types/literal-types.md
Creates the pretty syntax highlighting.
=> Language annotation on code block

docs/arrow-functions.md, docs/classes.md, docs/enums.md, docs/types/mixins.md
As with #562, this fixes the rendering of various numbered lists.
=> Fix more numbered list rendering

CONTRIBUTING.md
I think that `gitbook install` command is required.
=> fix contribute guide

docs/classes.md
Add the example code in the Abstract section to improve the explanation and help to understand how abstract classes work.
=> Update classes.md Abstract section.

README.md
Updated the download section so people would know how to download without going into the history of the issue raised for it
=> Updated README.md to show people where to download PDF, Epub, or Mobi files 

docs/let.md
Since surprises are enumerable, fewer is the grammatically correct choice.
=> Update let.md to replace lesser with fewer.

README.md
Hi. First of all, really great project. Here is a translation into Polish 🔥
https://github.com/mbiesiad/typescript-book/tree/pl_PL
@basarat 
Best wishes,
=> Add Polish

docs/iterators.md
=> fix broken generics link

docs/testing/jest.md
to work with 'ts-jest' we must install prerequisites
more [info](https://github.com/kulshekhar/ts-jest)
=> must install 'typescript' package for 'ts-jest'

docs/project/files.md
Either implies that there is an alternative (i.e. either...or) but this not clear from the sentence structure.
=> Change either to also

docs/styleguide/styleguide.md
Fix italic `Bad` and `Good` to maintain consistency
=> Fixed italic sub heading text to maintain consistency in Null vs Undefined section

README.md
Reference to the Thai translation
=> Update readme - Thai translation

docs/types/never.md
=> Correct a typo

README.md
Added reference on Ukrainian version of the repo
=> Added Ukrainian Translation Repo - Update README.md

.github/workflows/build.yml
Fix GitHub actions build fail error.
=> fix: missing the system library libEGL.so.1 error
