- docs/arrow-functions.md
- docs/classes.md
- docs/destructuring.md
- docs/for...of.md
- docs/let.md
- docs/spread-operator.md
- docs/template-strings.md
Hey, great book by the way :)
Just a few minor typos in the rest of the files.
> Minor typos

- docs/types/ambient/variables.md
there is a file (node.d.ts) referenced, but the text used to link it only displays node.ts.
> typo in variables.md

- docs/tips/bind.md
Fix typos ("loose" to "lose") in section 8.5: "Bind is Bad".
> Fix typos ("loose" to "lose")

- docs/tips/currying.md
Currying function is one that returns a series of unary methods.
It's a technique for achieving partial application of a function, altho in principle you can do that without currying the function.
> correct use of "curry"

- docs/types/readonly.md
Currently, readonly feature is not yet available; it is planned for version 2.0.
Without any warning, it can be confusing for people accessing this page directly (I just faced it).
> Added TypeScript version warning for readonly feature

- docs/types/freshness.md
Unrelated concern: the sentence starting with "The reason why only object literals are type checked this way is because" seemed a little difficult to parse. I thought I'd bring that to your attention, in case you want to simplify.
> Fix minor typos

- docs/tips/functionParameters.md
I took some liberties. Hope that's fine.
"Wrongly" isn't incorrect, but it's mostly used about moral.
> Fixed typos, grammar, phrasing in functionParameters

- docs/classes-emit.md
Sounds odd to my ear.
You might have also meant 
'This is called *prototypal inheritance* and is supported by JavaScript out of the box.
> 'is called to' vs. 'is said to'

- docs/jsx/tsx.md
typings should be deprecated in favor of npm registry '@types' namespace created by Microsoft
> Update Docs - JSX Support Page

- docs/classes.md
Order the columns and rows by 'permissiveness', in order to make it easier for people to see the pattern.
> Make the class access modifier table easier to grok

- docs/quick/browser.md
The script tag on index.html file reference to "./dist" path, but in webpack.config.js the output path is configured with "./build" path
> Change bundle.js output path

- docs/quick/browser.md
After executing webpack --watch throw the error:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema
.
- configuration.resolve.extensions[0] should not be empty.
Also in the example repo, is configured with out empty string extension: https://github.com/basarat/react-typescript/blob/master/webpack.config.js
> Config resolve extension should not be empty

- docs/types/discriminated-unions.md
Discriminated unions can be discriminated by enums as well, so I added a mention of that. Also added a missing word in a comment.
> Add enums to supported discriminators

- docs/types/ambient/variables.md
Currently pointing to old node.d.ts in a deprecated repo.
Should point to index.d.ts from the DefinitelyTypes repo.
See comments from blakeembrey @ https://github.com/basarat/typescript-book/pull/242
> Update deprecated node.d.ts to index.d.ts

- docs/promise.md
Promise.all and Promise.race are usually considered a pair, thus I added Promise.race for completeness.
> Add Promise.race for completeness

- docs/project/modules.md
Inferring from your argument, I believe you were trying to express: using `export` in foo.ts makes foo.ts a module, using `import` in bar.ts makes bar.ts a module.
> Correct a possible mistake.

- docs/quick/browser.md
The context-base should be "./" (the default value) in order to also serve "./index.html" and publicPath should be "/dist/" in order to still serve "./dist/bundle.js".
> Fixed webpack dev server configuration

- docs/types/lib.d.ts.md
- Lib defaults in TypeScript 2.3
- Add Symbol API when compiling with ES5 sample
> include some defaults for lib, and symbol sample

- docs/jsx/tsx.md
Look vaguely familiar?  
It should: https://github.com/Microsoft/TypeScript/issues/3960#issuecomment-165335501
> Describe use of generic components with JSX

- docs/promise.md
p2 presumably refers to task2 (promise2?), but task1 (p1 / promise1) actually will finish quicker.
> Fixed typo / clarified comment for Promise.race

- code/async-await/es5/asyncAwaitES5.js
- code/async-await/es5/asyncAwaitES5.ts
- code/async-await/es5/tsconfig.json
- code/async-await/es6/asyncAwaitES6.js
- code/async-await/es6/asyncAwaitES6.ts
- code/async-await/es6/tsconfig.json
- docs/async-await.md
Included:
- Edit https://github.com/basarat/typescript-book/blob/master/docs/async-await.md
- Include some folders with code samples for async await
> Async Await Support in TypeScript and samples

- SUMMARY.md
- docs/classes-emit.md
- docs/future-javascript.md
- docs/javascript/closure.md
- docs/project/external-modules.md
- docs/project/module-resolution.md
- docs/quick/browser.md
- docs/quick/nodejs.md
- docs/styleguide/styleguide.md
- docs/tips/typed-event.md
- docs/types/ambient/d.ts.md
- docs/types/exceptions.md
- docs/types/generics.md
Updated all instances of "NodeJS", "nodejs" to "Node.js" per Node.js trademark branding guidelines available at: https://nodejs.org/static/documents/trademark-policy.pdf
Excerpt from Section 5:
>You may only use Node.js wordmarks in their full form and properly capitalized (e.g. “Node.js”).
> Format all instances of Node.js wordmarks per trademark guidelines

- docs/types/callable.md
I think changing `number` to `num`, when comment says `num` is desired.
> Fix const name to avoid misunderstanding

- docs/types/callable.md
I felt like the example for making an interface for an overloaded function needs to show assignment compatibility with an actually overloaded function -- one declared with multiple type signatures.
In particular I was puzzling over whether an overloaded function should be an `&` type or an `|` type of its two signatures, and after trying it out it's clear it should be the `&` type.  I added that to make it clear as well.
I also added TypeScript syntax highlighting for all code snippets and touched up a few lines for clarity.
> Add overloaded function to go with overloaded callable interface

- docs/let.md
If the variable name is already taken by the surrounding scope then a new variable name is generated as shown foo_1 instead of _foo. https://github.com/basarat/typescript-book/issues/412
> A new way of creating an already existing variable in the surrounding scope. #412

- README.md
- docs/compiler/overview.md
- docs/compiler/scanner.md
- docs/project/dynamic-import-expressions.md
- docs/project/tsconfig.md
- docs/quick/nodejs.md
- docs/types/never.md
- docs/types/type-assertion.md
- docs/types/type-system.md
- docs/why-typescript.md
Where appropriate:
Change 'typescript' to correct proper noun form 'TypeScript'
Change 'javascript' to correct proper noun form 'JavaScript'
> Update typescript -> TypeScript

- docs/generators.md
Generators can be transpiled to ES5 since TS 2.3: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generators
> Remove the note about generators being unavailable

- docs/types/never.md
The original statement, "never can only ever be assigned to another never," implies the following is not allowed:
```ts
let bar: never;
let foo: number = bar // statement implies this is not allowed
```
> Modify wording of never assignability

- docs/iterators.md
I noticed when defining `frame.next()` it returns a type error since it can return `{ done : true }` when the type requires `{ done: boolean, value: T }`
> Fix example in iterators section

- docs/generators.md
Document the problems with two-way communication in generators, as the next function accepts a parameter of any type and so the result of the yield operator is always of type any.
> The result of a yield operator always has type any

- docs/project/external-modules.md
Without the newline, the code is part of li element and is indented from left.
> fix code block indentation

- docs/tips/typed-event.md
Added additional condition to `emit` method where the `listenersOncer` will be processed only if there is something available.
It helps with performance. In this case it won't assign on each `emit` call the empty array.
> Extended TypedEvent example class

- docs/tools/eslint.md
Otherwise an error will be thrown from eslint: `No files matching the pattern "src/<directory>" were found.`
> Fix example linting command

- code/types/freshness/freshness.ts
- docs/types/freshness.md
The last examples in Freshness had incorrect closing parentheses. While fixing them I noticed those same examples were missing on `/code`, so I added them inside a fake class to allow the editor to detect future errors.
> Freshness typos

- docs/tips/nominalTyping.md
Addresses: https://github.com/basarat/typescript-book/issues/521
Uses technique from: https://github.com/microsoft/TypeScript/issues/32891
Also note: This "& string" that remains in this code sample appears to do nothing as of TypeScript 3.6.2, but presumably should be kept for backwards compat.
> Fix Nominal Typing for TypeScript 3.6.2 by forcing enums to be string enums

- docs/template-strings.md
Update "Template Strings" section to reflect the latest official naming of "Template Literals".
Wasn't sure how far this should go in the way things were originally written to describe this feature, and didn't want to rename the filename in case it would affect any URL's or links.
> Rename "Template Strings" to "Template Literals"

- docs/javascript/null-undefined.md
"can save **_of_** storage and transmission costs" > "can save **_on_** storage and transmission costs"
> Fix typo in "Null vs. Undefined" section

- docs/testing/jest.md
I've just setting up test for my projects and there was a message about `"setupTestFrameworkScriptFile" is depercated`
Additinally `import * as EnzymeAdapter from 'enzyme-adapter-react-16';` do not working too, need to use default import
> Up to date jest.md

- docs/project/external-modules.md
In the "Use case: Ensure Import" section code example, ensure that all of these are imported by using `&&` instead of `||`.
> Update Code Example in "Use case: Ensure Import"

- docs/tips/defaultIsBad.md
Is looks like in sample where HighCharts dynamic import() used there are missed 's' in two places.
> Update defaultIsBad.md and change HighChart => HighCharts

- docs/jsx/react.md
Hello. 🌹 
I've found a dead link in [this section](https://basarat.gitbooks.io/typescript/docs/jsx/react.html#type-assertions) and fixed it to be a link to [this section](https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html#as-foo-vs-foo), the place it used to link to.
> Fix stale path to type-assertion.md

- docs/testing/jest.md
Hello, first-time contributor here.
This commit removes a regex quantifier from suggested Jest's `transform` matcher. This quantifier (the character `?`) would match files that otherwise shouldn't be matched by Jest.
As you can see in the screenshot below, the quantifier makes the whole extension optional:
[![](https://user-images.githubusercontent.com/673884/69070423-e1a52700-0a06-11ea-8ec3-407bdd5f141e.png)](https://user-images.githubusercontent.com/673884/69070423-e1a52700-0a06-11ea-8ec3-407bdd5f141e.png)
> Removes quantifier from Jest's `transform` regex

- SUMMARY.md
- docs/project/external-modules.md
- docs/project/globals.md
- docs/types/ambient/d.ts.md
- docs/types/lib.d.ts.md
- docs/types/migrating.md
I think you want to use `global.d.ts` for putting interfaces / types in the global namespace.
> rename 'globals.d.ts' to 'global.d.ts'

- .github/workflows/build.yml
Build on each new commits in master branch.
The generated files can be downloaded under actions artifacts section.
The idea is from the discussion in #550
This is just an experiment. I think it can be more useful by publishing as release (also achievable via github actions).
> Build ebooks (pdf, epub and mobi) using github actions

- docs/why-typescript.md
As written, this list doesn't render as bullets, and instead collapses into a single paragraph. This change breaks the list into its own paragraph so that it can be parsed as such.
> Fix numbered list rendering

- docs/testing/jest.md
This improves the rendering of code blocks inside lists, by ensuring that the code blocks are treated as children of the list items. This also fixes numbering.
> Fix nesting of code blocks under lists

- docs/types/index-signatures.md
Currently, `[key: string]: number` is not reflected on the screen.
Adding a trailing semicolon may eliminate this bug.
Unfortunately, this problem does not occur in the local environment, so it is difficult to verify.
In any case, I think it is better to add a semicolon.
*current screen*
> fix sample code of index signature

- docs/types/index-signatures.md
There was just a small typo in this file where an `or` should be an `of`
Thanks for the great descriptions.
> Fix minor type-o in index-signatures.md

- docs/types/type-inference.md
Renamed `a` parameter in function `addOne` to `c`, to remove ambiguity with `a` parameter in function `foo`.
> Removed name ambiguity in a function

- docs/project/globals.md
The `global.d.ts` file can be used for more than "beginner TypeScript developer" hand-holding. In fact, the latter is something that should probably be discouraged :-)
I updated the document to include a use case for compile-time constants when using Webpack, and also tidied up some related information.
> Extended the use case for the global.d.ts file

- docs/testing/jest.md
Modules, and their continual evolution, are hell.  Unless tooling gets better at inferring module types, examples will have to account for differing module requirements.  Yuck.  I wish this were a part of JavaScript experience that the TypeScript team had taken a bigger role in improving.
> Augment sample config with es6 module help

- docs/jsx/react.md
now that `unknown` exists, this is the most desirable way to do things https://github.com/typescript-eslint/typescript-eslint/issues/2191
> updates example of generic jsx arrow function to use `unknown`

- docs/project/external-modules.md
When `module` is set to `commonjs`, `moduleResolution ` becomes `Node`.
> Fix moduleResolution explain

- docs/javascript/null-undefined.md
"Remember how I said you should use `== null` " is shorthand for the rhetorical question "Do you remember remember how I said you should use `== null`?", with the question answered in the following sentence. We should therefore add a question mark.
> Fix: Replace full stop with question mark

- docs/jsx/react.md
As of [@types/react PR #46643](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46643), you can use a new `React.VoidFunctionComponent` or `React.VFC` type if you wish to declare the accepted `children` explicitly.
> Add Void Function Components

- docs/quick/nodejs.md
```
[nodemon] starting `'ts-node' src/index.ts`
''ts-node'' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
[nodemon] app crashed - waiting for file changes before starting...
```
ts-node command not found.
It didn't work unless it was double quotes.
OS: windows10
> fixed documentation scripts

- docs/tips/nominalTyping.md
added code (``) escape to better demonstrate the character
> nominalTyping: Fix unintended italics due to _

- docs/types/freshness.md
I think this is a much better practice, as it will prevent the developer from doing something like: 
```
function logIfHasName(something: { name?: string, [key: string]: unknown}) {
if (something.name) {
console.log(something.name);
console.log(something.foo.bar); //Object is of type 'unknown'.(2571)
}
}
```
As opposed to 
```
function logIfHasName2(something: { name?: string, [key: string]: any}) {
if (something.name) {
console.log(something.name);
console.log(something.foo.bar); //is allowed
}
}
```
https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAGzgcwJLABIEMDOAcrgLYCmAFPnOVABYxhoBciA3omKWQPyv5QATozQAaRAG0A1mQCe-ISIC6rcFLBwA7mAC+ASnYAoRCcQxgiKjTL0RAOi7kDbY6bcQE1ZGTuo0V2gYmB249AG5XNxMPMC8fPwCbILQ7YDg4OwAjXEFwxAB6fIB5TIArMmgzfEQ4CyhZAAcyRAByNQ1tFrsKACYAVgB2AEY9SMQdQwnDUEhYBBR0LD …
> Change 'extra properties' type from `any` to `unknown`

- .github/workflows/build.yml
Explicitly specify latest version of nodejs which is compatible with abandoned 'gitbook-cli' v2.3.2
Fixes #610
> nodejs version compatible with gitbook-cli
